server:
  port: 8083

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq

  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=payment
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect